name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'fix'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Maintenance'
    label: 'maintenance'
