name: Build and test

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and test

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres_test # "_test" is required for fixtures
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test
        env:
          SONAR_DB: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres_test?sslmode=disable'

