name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish docker image
      run: make docker-release docker_login=bizonebot docker_password=${{ secrets.GITHUB_TOKEN }}
